/*
**
** The C code is generated by ATS/Postiats
** The compilation time is: 2014-8-14: 13h: 6m
**
*/

/*
** include runtime header files
*/
#ifndef _ATS_CCOMP_HEADER_NONE
#include "pats_ccomp_config.h"
#include "pats_ccomp_basics.h"
#include "pats_ccomp_typedefs.h"
#include "pats_ccomp_instrset.h"
#include "pats_ccomp_memalloc.h"
#ifndef _ATS_CCOMP_EXCEPTION_NONE
#include "pats_ccomp_memalloca.h"
#include "pats_ccomp_exception.h"
#endif // end of [_ATS_CCOMP_EXCEPTION_NONE]
#endif /* _ATS_CCOMP_HEADER_NONE */


/*
** include prelude cats files
*/
#ifndef _ATS_CCOMP_PRELUDE_NONE
//
#include "prelude/CATS/basics.cats"
#include "prelude/CATS/integer.cats"
#include "prelude/CATS/pointer.cats"
#include "prelude/CATS/bool.cats"
#include "prelude/CATS/char.cats"
#include "prelude/CATS/integer_ptr.cats"
#include "prelude/CATS/integer_fixed.cats"
#include "prelude/CATS/float.cats"
#include "prelude/CATS/memory.cats"
#include "prelude/CATS/string.cats"
#include "prelude/CATS/strptr.cats"
//
#include "prelude/CATS/filebas.cats"
//
#include "prelude/CATS/list.cats"
#include "prelude/CATS/option.cats"
#include "prelude/CATS/array.cats"
#include "prelude/CATS/arrayptr.cats"
#include "prelude/CATS/arrayref.cats"
#include "prelude/CATS/matrix.cats"
#include "prelude/CATS/matrixptr.cats"
//
#endif /* _ATS_CCOMP_PRELUDE_NONE */
/*
** for user-supplied prelude
*/
#ifdef _ATS_CCOMP_PRELUDE_USER
//
#include _ATS_CCOMP_PRELUDE_USER
//
#endif /* _ATS_CCOMP_PRELUDE_USER */

/*
staload-prologues(beg)
*/
/*
/usr/local/Cellar/ats011/0.1.1/lib/ats2-postiats-0.1.1/prelude/DATS/pointer.dats: 1533(line=44, offs=1) -- 1572(line=44, offs=40)
*/
/*
/usr/local/Cellar/ats011/0.1.1/lib/ats2-postiats-0.1.1/prelude/DATS/integer.dats: 1636(line=51, offs=1) -- 1675(line=51, offs=40)
*/
/*
/usr/local/Cellar/ats011/0.1.1/lib/ats2-postiats-0.1.1/prelude/DATS/integer_fixed.dats: 1641(line=51, offs=1) -- 1680(line=51, offs=40)
*/
/*
/usr/local/Cellar/ats011/0.1.1/lib/ats2-postiats-0.1.1/prelude/DATS/memory.dats: 1410(line=38, offs=1) -- 1449(line=39, offs=32)
*/
/*
/usr/local/Cellar/ats011/0.1.1/lib/ats2-postiats-0.1.1/prelude/DATS/string.dats: 1609(line=48, offs=1) -- 1648(line=48, offs=40)
*/
/*
/usr/local/Cellar/ats011/0.1.1/lib/ats2-postiats-0.1.1/prelude/DATS/strptr.dats: 1609(line=48, offs=1) -- 1648(line=48, offs=40)
*/
/*
/usr/local/Cellar/ats011/0.1.1/lib/ats2-postiats-0.1.1/prelude/DATS/strptr.dats: 1671(line=52, offs=1) -- 1718(line=52, offs=48)
*/
/*
/usr/local/Cellar/ats011/0.1.1/lib/ats2-postiats-0.1.1/prelude/DATS/integer.dats: 1636(line=51, offs=1) -- 1675(line=51, offs=40)
*/
/*
/usr/local/Cellar/ats011/0.1.1/lib/ats2-postiats-0.1.1/prelude/DATS/filebas.dats: 1613(line=48, offs=1) -- 1652(line=48, offs=40)
*/
/*
/usr/local/Cellar/ats011/0.1.1/lib/ats2-postiats-0.1.1/prelude/DATS/filebas.dats: 1675(line=52, offs=1) -- 1722(line=52, offs=48)
*/
/*
/usr/local/Cellar/ats011/0.1.1/lib/ats2-postiats-0.1.1/prelude/DATS/integer.dats: 1636(line=51, offs=1) -- 1675(line=51, offs=40)
*/
/*
/usr/local/Cellar/ats011/0.1.1/lib/ats2-postiats-0.1.1/prelude/DATS/filebas.dats: 1745(line=56, offs=1) -- 1783(line=56, offs=39)
*/
/*
/usr/local/Cellar/ats011/0.1.1/lib/ats2-postiats-0.1.1/libc/SATS/stdio.sats: 1380(line=35, offs=1) -- 1418(line=37, offs=3)
*/

#include "libc/CATS/stdio.cats"
/*
/usr/local/Cellar/ats011/0.1.1/lib/ats2-postiats-0.1.1/libc/SATS/stdio.sats: 1791(line=56, offs=1) -- 1833(line=58, offs=27)
*/
/*
/usr/local/Cellar/ats011/0.1.1/lib/ats2-postiats-0.1.1/libc/sys/SATS/types.sats: 1390(line=36, offs=1) -- 1432(line=38, offs=3)
*/

#include "libc/sys/CATS/types.cats"
/*
/usr/local/Cellar/ats011/0.1.1/lib/ats2-postiats-0.1.1/prelude/DATS/filebas.dats: 1861(line=61, offs=1) -- 1901(line=61, offs=41)
*/
/*
/usr/local/Cellar/ats011/0.1.1/lib/ats2-postiats-0.1.1/libc/sys/SATS/stat.sats: 1390(line=36, offs=1) -- 1431(line=38, offs=3)
*/

#include "libc/sys/CATS/stat.cats"
/*
/usr/local/Cellar/ats011/0.1.1/lib/ats2-postiats-0.1.1/libc/sys/SATS/stat.sats: 1776(line=53, offs=1) -- 1818(line=54, offs=35)
*/
/*
/usr/local/Cellar/ats011/0.1.1/lib/ats2-postiats-0.1.1/libc/sys/SATS/types.sats: 1390(line=36, offs=1) -- 1432(line=38, offs=3)
*/

#include "libc/sys/CATS/types.cats"
/*
/usr/local/Cellar/ats011/0.1.1/lib/ats2-postiats-0.1.1/prelude/DATS/filebas.dats: 15159(line=816, offs=1) -- 15189(line=816, offs=31)
*/
/*
/usr/local/Cellar/ats011/0.1.1/lib/ats2-postiats-0.1.1/libc/SATS/stdio.sats: 1380(line=35, offs=1) -- 1418(line=37, offs=3)
*/

#include "libc/CATS/stdio.cats"
/*
/usr/local/Cellar/ats011/0.1.1/lib/ats2-postiats-0.1.1/libc/SATS/stdio.sats: 1791(line=56, offs=1) -- 1833(line=58, offs=27)
*/
/*
/usr/local/Cellar/ats011/0.1.1/lib/ats2-postiats-0.1.1/libc/sys/SATS/types.sats: 1390(line=36, offs=1) -- 1432(line=38, offs=3)
*/

#include "libc/sys/CATS/types.cats"
/*
/usr/local/Cellar/ats011/0.1.1/lib/ats2-postiats-0.1.1/prelude/DATS/list.dats: 1527(line=44, offs=1) -- 1566(line=44, offs=40)
*/
/*
/usr/local/Cellar/ats011/0.1.1/lib/ats2-postiats-0.1.1/prelude/DATS/list.dats: 1567(line=45, offs=1) -- 1613(line=45, offs=47)
*/
/*
/usr/local/Cellar/ats011/0.1.1/lib/ats2-postiats-0.1.1/prelude/DATS/unsafe.dats: 1532(line=44, offs=1) -- 1566(line=44, offs=35)
*/
/*
/usr/local/Cellar/ats011/0.1.1/lib/ats2-postiats-0.1.1/prelude/DATS/list_vt.dats: 1536(line=44, offs=1) -- 1575(line=44, offs=40)
*/
/*
/usr/local/Cellar/ats011/0.1.1/lib/ats2-postiats-0.1.1/prelude/DATS/list_vt_mergesort.dats: 1546(line=44, offs=1) -- 1585(line=44, offs=40)
*/
/*
/usr/local/Cellar/ats011/0.1.1/lib/ats2-postiats-0.1.1/prelude/DATS/list_vt_quicksort.dats: 1546(line=44, offs=1) -- 1585(line=44, offs=40)
*/
/*
/usr/local/Cellar/ats011/0.1.1/lib/ats2-postiats-0.1.1/prelude/DATS/array.dats: 1534(line=44, offs=1) -- 1573(line=44, offs=40)
*/
/*
/usr/local/Cellar/ats011/0.1.1/lib/ats2-postiats-0.1.1/prelude/DATS/array.dats: 1574(line=45, offs=1) -- 1616(line=45, offs=43)
*/
/*
/usr/local/Cellar/ats011/0.1.1/lib/ats2-postiats-0.1.1/prelude/DATS/array_bsearch.dats: 1531(line=44, offs=1) -- 1570(line=44, offs=40)
*/
/*
/usr/local/Cellar/ats011/0.1.1/lib/ats2-postiats-0.1.1/prelude/DATS/array_quicksort.dats: 1531(line=44, offs=1) -- 1570(line=44, offs=40)
*/
/*
/usr/local/Cellar/ats011/0.1.1/lib/ats2-postiats-0.1.1/prelude/DATS/arrayptr.dats: 1532(line=44, offs=1) -- 1571(line=44, offs=40)
*/
/*
/usr/local/Cellar/ats011/0.1.1/lib/ats2-postiats-0.1.1/prelude/DATS/arrayref.dats: 1532(line=44, offs=1) -- 1571(line=44, offs=40)
*/
/*
/usr/local/Cellar/ats011/0.1.1/lib/ats2-postiats-0.1.1/prelude/DATS/matrix.dats: 1535(line=44, offs=1) -- 1574(line=44, offs=40)
*/
/*
/usr/local/Cellar/ats011/0.1.1/lib/ats2-postiats-0.1.1/prelude/DATS/matrixptr.dats: 1538(line=44, offs=1) -- 1577(line=44, offs=40)
*/
/*
/usr/local/Cellar/ats011/0.1.1/lib/ats2-postiats-0.1.1/prelude/DATS/matrixref.dats: 1538(line=44, offs=1) -- 1577(line=44, offs=40)
*/
/*
/usr/local/Cellar/ats011/0.1.1/lib/ats2-postiats-0.1.1/prelude/DATS/stream.dats: 1570(line=48, offs=1) -- 1609(line=48, offs=40)
*/
/*
/usr/local/Cellar/ats011/0.1.1/lib/ats2-postiats-0.1.1/prelude/DATS/stream_vt.dats: 1573(line=48, offs=1) -- 1612(line=48, offs=40)
*/
/*
/usr/local/Cellar/ats011/0.1.1/lib/ats2-postiats-0.1.1/prelude/DATS/unsafe.dats: 1532(line=44, offs=1) -- 1566(line=44, offs=35)
*/
/*
/usr/local/Cellar/ats011/0.1.1/lib/ats2-postiats-0.1.1/prelude/DATS/checkast.dats: 1531(line=44, offs=1) -- 1570(line=45, offs=32)
*/
/*
staload-prologues(end)
*/
/*
typedefs-for-tyrecs-and-tysums(beg)
*/
typedef
struct {
#if(1)
int contag ;
#endif
atstkind_t0ype(atstype_int) atslab__0; 
} postiats_tysum_0 ;
typedef
struct {
#if(1)
int contag ;
#endif
atstype_boxed atslab__0; 
atstype_boxed atslab__1; 
} postiats_tysum_1 ;
/*
typedefs-for-tyrecs-and-tysums(end)
*/
/*
dynconlst-declaration(beg)
*/
/*
dynconlst-declaration(end)
*/
/*
dyncstlst-declaration(beg)
*/
ATSdyncst_mac(atspre_g0int_add_int)
ATSdyncst_mac(atspre_print_int)
ATSdyncst_mac(atspre_print_newline)
/*
dyncstlst-declaration(end)
*/
/*
dynvalist-implementation(beg)
*/
/*
dynvalist-implementation(end)
*/
/*
exnconlst-declaration(beg)
*/
#ifndef _ATS_CCOMP_EXCEPTION_NONE
extern void the_atsexncon_initize (atstype_exncon *d2c, char *exnmsg) ;
#endif // end of [_ATS_CCOMP_EXCEPTION_NONE]
/*
exnconlst-declaration(end)
*/
/*
assumelst-declaration(beg)
*/
/*
assumelst-declaration(end)
*/
/*
extypelst-declaration(beg)
*/
/*
extypelst-declaration(end)
*/
ATSstaticdec()
atstkind_t0ype(atstype_int)
eval_0(atstype_boxed) ;

#if(0)
ATSglobaldec()
atsvoid_t0ype
mainats_void_0() ;
#endif // end of [QUALIFIED]

/*
/Users/sakurai/git/ats/calc.dats: 124(line=9, offs=5) -- 264(line=14, offs=6)
*/
/*
local: eval_0$0(level=0)
global: eval_0$0(level=0)
local: 
global: 
*/
ATSstaticdec()
atstkind_t0ype(atstype_int)
eval_0(atstype_boxed arg0)
{
/* tmpvardeclst(beg) */
ATStmpdec(tmpret0, atstkind_t0ype(atstype_int)) ;
ATStmpdec(tmp1, atstkind_t0ype(atstype_int)) ;
ATStmpdec(tmp2, atstype_boxed) ;
ATStmpdec(tmp3, atstype_boxed) ;
ATStmpdec(tmp4, atstype_boxed) ;
ATStmpdec(tmp5, atstype_boxed) ;
ATStmpdec(tmp6, atstkind_t0ype(atstype_int)) ;
ATStmpdec(tmp7, atstkind_t0ype(atstype_int)) ;
ATStmpdec(tmp8, atstkind_t0ype(atstype_int)) ;
ATStmpdec(tmp9, atstkind_t0ype(atstype_int)) ;
/* tmpvardeclst(end) */
/* funbodyinstrlst(beg) */
/*
emit_instr: loc0 = /Users/sakurai/git/ats/calc.dats: 124(line=9, offs=5) -- 264(line=14, offs=6)
*/
ATSINSlab(__patsflab_eval_0):
/*
emit_instr: loc0 = /Users/sakurai/git/ats/calc.dats: 152(line=10, offs=9) -- 258(line=13, offs=38)
*/
ATScaseofbeg()
/*
** ibranchlst-beg
*/
ATSbranchbeg() ;
/*
emit_instr: loc0 = /Users/sakurai/git/ats/calc.dats: 170(line=11, offs=7) -- 176(line=11, offs=13)
*/
__atstmplab0:
/*
emit_instr: loc0 = /Users/sakurai/git/ats/calc.dats: 129(line=9, offs=10) -- 132(line=9, offs=13)
*/
ATSifnot(ATSPATCKcon1(arg0, 0)) { ATSgoto(__atstmplab2) ; }
/*
emit_instr: loc0 = /Users/sakurai/git/ats/calc.dats: 176(line=11, offs=13) -- 176(line=11, offs=13)
*/
__atstmplab1:
/*
emit_instr: loc0 = /Users/sakurai/git/ats/calc.dats: 175(line=11, offs=12) -- 176(line=11, offs=13)
*/
ATSINSmove(tmp1, ATSSELcon(arg0, postiats_tysum_0, atslab__0)) ;
/*
emit_instr: loc0 = : 0(line=0, offs=0) -- 0(line=0, offs=0)
*/
/*
ibranch-mbody:
*/
/*
emit_instr: loc0 = /Users/sakurai/git/ats/calc.dats: 181(line=11, offs=18) -- 182(line=11, offs=19)
*/
ATSINSmove(tmpret0, tmp1) ;
ATSbranchend() ;

ATSbranchbeg() ;
/*
emit_instr: loc0 = /Users/sakurai/git/ats/calc.dats: 189(line=12, offs=7) -- 199(line=12, offs=17)
*/
__atstmplab2:
/*
emit_instr: loc0 = /Users/sakurai/git/ats/calc.dats: 129(line=9, offs=10) -- 132(line=9, offs=13)
*/
ATSifnot(ATSPATCKcon1(arg0, 1)) { ATSgoto(__atstmplab4) ; }
/*
emit_instr: loc0 = /Users/sakurai/git/ats/calc.dats: 199(line=12, offs=17) -- 199(line=12, offs=17)
*/
__atstmplab3:
/*
emit_instr: loc0 = /Users/sakurai/git/ats/calc.dats: 194(line=12, offs=12) -- 195(line=12, offs=13)
*/
ATSINSmove(tmp2, ATSSELcon(arg0, postiats_tysum_1, atslab__0)) ;
/*
emit_instr: loc0 = /Users/sakurai/git/ats/calc.dats: 197(line=12, offs=15) -- 198(line=12, offs=16)
*/
ATSINSmove(tmp3, ATSSELcon(arg0, postiats_tysum_1, atslab__1)) ;
/*
emit_instr: loc0 = : 0(line=0, offs=0) -- 0(line=0, offs=0)
*/
/*
ibranch-mbody:
*/
/*
emit_instr: loc0 = /Users/sakurai/git/ats/calc.dats: 203(line=12, offs=21) -- 209(line=12, offs=27)
*/
ATSINSmove(tmp6, eval_0(tmp2)) ;

/*
emit_instr: loc0 = /Users/sakurai/git/ats/calc.dats: 213(line=12, offs=31) -- 219(line=12, offs=37)
*/
ATSINSmove(tmp7, eval_0(tmp3)) ;

/*
emit_instr: loc0 = /Users/sakurai/git/ats/calc.dats: 203(line=12, offs=21) -- 219(line=12, offs=37)
*/
ATSINSmove(tmpret0, atspre_g0int_add_int(tmp6, tmp7)) ;

ATSbranchend() ;

ATSbranchbeg() ;
/*
emit_instr: loc0 = /Users/sakurai/git/ats/calc.dats: 227(line=13, offs=7) -- 237(line=13, offs=17)
*/
__atstmplab4:
/*
emit_instr: loc0 = /Users/sakurai/git/ats/calc.dats: 129(line=9, offs=10) -- 132(line=9, offs=13)
*/
ATSifnot(ATSPATCKcon1(arg0, 2)) { ATSINScaseof_fail("/Users/sakurai/git/ats/calc.dats: 152(line=10, offs=9) -- 258(line=13, offs=38)") ; }
/*
emit_instr: loc0 = /Users/sakurai/git/ats/calc.dats: 237(line=13, offs=17) -- 237(line=13, offs=17)
*/
__atstmplab5:
/*
emit_instr: loc0 = /Users/sakurai/git/ats/calc.dats: 232(line=13, offs=12) -- 233(line=13, offs=13)
*/
ATSINSmove(tmp4, ATSSELcon(arg0, postiats_tysum_1, atslab__0)) ;
/*
emit_instr: loc0 = /Users/sakurai/git/ats/calc.dats: 235(line=13, offs=15) -- 236(line=13, offs=16)
*/
ATSINSmove(tmp5, ATSSELcon(arg0, postiats_tysum_1, atslab__1)) ;
/*
emit_instr: loc0 = : 0(line=0, offs=0) -- 0(line=0, offs=0)
*/
/*
ibranch-mbody:
*/
/*
emit_instr: loc0 = /Users/sakurai/git/ats/calc.dats: 241(line=13, offs=21) -- 247(line=13, offs=27)
*/
ATSINSmove(tmp8, eval_0(tmp4)) ;

/*
emit_instr: loc0 = /Users/sakurai/git/ats/calc.dats: 251(line=13, offs=31) -- 257(line=13, offs=37)
*/
ATSINSmove(tmp9, eval_0(tmp5)) ;

/*
emit_instr: loc0 = /Users/sakurai/git/ats/calc.dats: 241(line=13, offs=21) -- 257(line=13, offs=37)
*/
ATSINSmove(tmpret0, atspre_g0int_add_int(tmp8, tmp9)) ;

ATSbranchend() ;

/*
** ibranchlst-end
*/
ATScaseofend()

/* funbodyinstrlst(end) */
ATSreturn(tmpret0) ;
} /* end of [eval_0] */

/*
/Users/sakurai/git/ats/calc.dats: 281(line=16, offs=16) -- 352(line=18, offs=2)
*/
/*
local: eval_0$0(level=0)
global: eval_0$0(level=0), mainats_void_0$2$0(level=0)
local: 
global: 
*/
ATSglobaldec()
atsvoid_t0ype
mainats_void_0()
{
/* tmpvardeclst(beg) */
ATStmpdec_void(tmpret10, atsvoid_t0ype) ;
ATStmpdec_void(tmp11, atsvoid_t0ype) ;
ATStmpdec(tmp12, atstkind_t0ype(atstype_int)) ;
ATStmpdec(tmp13, atstype_boxed) ;
ATStmpdec(tmp14, atstype_boxed) ;
ATStmpdec(tmp15, atstype_boxed) ;
ATStmpdec(tmp16, atstype_boxed) ;
ATStmpdec(tmp17, atstype_boxed) ;
/* tmpvardeclst(end) */
/* funbodyinstrlst(beg) */
/*
emit_instr: loc0 = /Users/sakurai/git/ats/calc.dats: 276(line=16, offs=11) -- 352(line=18, offs=2)
*/
ATSINSlab(__patsflab_main_void_0):
/*
emit_instr: loc0 = /Users/sakurai/git/ats/calc.dats: 286(line=16, offs=21) -- 352(line=18, offs=2)
*/
/*
letpush(beg)
*/
/*
letpush(end)
*/

/*
emit_instr: loc0 = /Users/sakurai/git/ats/calc.dats: 323(line=17, offs=36) -- 329(line=17, offs=42)
*/

ATSINSmove_con1(tmp15, postiats_tysum_0) ;
#if(1)
ATSINSstore_con_tag(tmp15, 0) ;
#endif
ATSINSstore_con_ofs(tmp15, postiats_tysum_0, atslab__0, ATSPMVi0nt(1)) ;

/*
emit_instr: loc0 = /Users/sakurai/git/ats/calc.dats: 331(line=17, offs=44) -- 337(line=17, offs=50)
*/

ATSINSmove_con1(tmp16, postiats_tysum_0) ;
#if(1)
ATSINSstore_con_tag(tmp16, 0) ;
#endif
ATSINSstore_con_ofs(tmp16, postiats_tysum_0, atslab__0, ATSPMVi0nt(2)) ;

/*
emit_instr: loc0 = /Users/sakurai/git/ats/calc.dats: 318(line=17, offs=31) -- 339(line=17, offs=52)
*/

ATSINSmove_con1(tmp14, postiats_tysum_1) ;
#if(1)
ATSINSstore_con_tag(tmp14, 1) ;
#endif
ATSINSstore_con_ofs(tmp14, postiats_tysum_1, atslab__0, tmp15) ;
ATSINSstore_con_ofs(tmp14, postiats_tysum_1, atslab__1, tmp16) ;

/*
emit_instr: loc0 = /Users/sakurai/git/ats/calc.dats: 340(line=17, offs=53) -- 346(line=17, offs=59)
*/

ATSINSmove_con1(tmp17, postiats_tysum_0) ;
#if(1)
ATSINSstore_con_tag(tmp17, 0) ;
#endif
ATSINSstore_con_ofs(tmp17, postiats_tysum_0, atslab__0, ATSPMVi0nt(1)) ;

/*
emit_instr: loc0 = /Users/sakurai/git/ats/calc.dats: 313(line=17, offs=26) -- 348(line=17, offs=61)
*/

ATSINSmove_con1(tmp13, postiats_tysum_1) ;
#if(1)
ATSINSstore_con_tag(tmp13, 2) ;
#endif
ATSINSstore_con_ofs(tmp13, postiats_tysum_1, atslab__0, tmp14) ;
ATSINSstore_con_ofs(tmp13, postiats_tysum_1, atslab__1, tmp17) ;

/*
emit_instr: loc0 = /Users/sakurai/git/ats/calc.dats: 308(line=17, offs=21) -- 348(line=17, offs=61)
*/
ATSINSmove(tmp12, eval_0(tmp13)) ;

/*
emit_instr: loc0 = /Users/sakurai/git/ats/calc.dats: 299(line=17, offs=12) -- 350(line=17, offs=63)
*/
ATSINSmove_void(tmp11, atspre_print_int(tmp12)) ;

/*
emit_instr: loc0 = /Users/sakurai/git/ats/calc.dats: 299(line=17, offs=12) -- 350(line=17, offs=63)
*/
ATSINSmove_void(tmpret10, atspre_print_newline()) ;

/*
emit_instr: loc0 = /Users/sakurai/git/ats/calc.dats: 286(line=16, offs=21) -- 352(line=18, offs=2)
*/
/*
INSletpop()
*/
/* funbodyinstrlst(end) */
ATSreturn_void(tmpret10) ;
} /* end of [mainats_void_0] */

/*
** for initialization(dynloading)
*/
atsvoid_t0ype
_057_Users_057_sakurai_057_git_057_ats_057_calc_056_dats__dynload()
{
ATSdynload0(
_057_Users_057_sakurai_057_git_057_ats_057_calc_056_dats__dynloadflag
) ;
ATSif(
ATSCKiseqz(
_057_Users_057_sakurai_057_git_057_ats_057_calc_056_dats__dynloadflag
)
) ATSthen() {
ATSdynloadset(_057_Users_057_sakurai_057_git_057_ats_057_calc_056_dats__dynloadflag) ;
/*
dynexnlst-initize(beg)
*/
/*
dynexnlst-initize(end)
*/
} /* ATSendif */
ATSreturn_void() ;
} /* end of [*_dynload] */

/*
** the ATS runtime
*/
#ifndef _ATS_CCOMP_RUNTIME_NONE
#include "pats_ccomp_runtime.c"
#include "pats_ccomp_runtime_memalloc.c"
#ifndef _ATS_CCOMP_EXCEPTION_NONE
#include "pats_ccomp_runtime2_dats.c"
#ifndef _ATS_CCOMP_RUNTIME_TRYWITH_NONE
#include "pats_ccomp_runtime_trywith.c"
#endif /* _ATS_CCOMP_RUNTIME_TRYWITH_NONE */
#endif // end of [_ATS_CCOMP_EXCEPTION_NONE]
#endif /* _ATS_CCOMP_RUNTIME_NONE */

/*
** the [main] implementation
*/
int
main
(
int argc, char **argv, char **envp
) {
int err = 0 ;
_057_Users_057_sakurai_057_git_057_ats_057_calc_056_dats__dynload() ;
ATSmainats_void_0(err) ;
return (err) ;
} /* end of [main] */
